name: new_proj
description: "PillPal - Smart Medication Management System"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:

  flutter:
    sdk: flutter

  # Core Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3
  timezone: ^0.9.2
  alarm: ^3.0.0

  # Notifications
  flutter_local_notifications: ^17.2.2
  
  # Audio
  audioplayers: ^6.0.0
  
  # BLE for ESP32 communication
  flutter_blue_plus: ^1.31.2
  
  # MQTT for IoT communication
  mqtt_client: ^10.3.2
  
  # Logger
  logger: ^2.4.0

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # UI & Fonts
  google_fonts: ^6.2.1
  fl_chart: ^0.69.0
  
  # Utilities
  intl: ^0.19.0
  shared_preferences: ^2.3.3
  
  # PDF Generation
  pdf: ^3.11.1
  path_provider: ^2.1.4
  open_filex: ^4.5.0
  printing: ^5.13.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/alarm_sound.mp3